### ISSUE TITLE
ENOENT Error on npm3

### ISSUE THREAD

**Issue by e-jigsaw** [sindresorhus/gulp-ava#2]
Hi

`ava` binary placed on `(project root)/node_modules/.bin/ava` on npm3.

```
var BIN = path.join(__dirname, 'node_modules', '.bin', 'ava');
```

raises ENOENT error. How to fix this?

Thanks

**Comment by vdemedes** [comment]
Hey,

This is caused by the way npm3 installs dependencies, it tries to put them as flat as possible. So, gulp-ava can't find ava executable.

Thanks for reporting this, fix will be submitted soon.

**Comment by kevva** [comment]
Doesn't all executables get put in `.bin` though?

**Comment by vdemedes** [comment]
@kevva Yes, they are, but gulp-ava looks for .bin inside its own node_modules - https://github.com/sindresorhus/gulp-ava/blob/master/index.js#L6

**Comment by kevva** [comment]
Oh, yeah...

**Comment by shinnn** [comment]
`require.resolve` would help us:

```js
require.resolve('ava/cli.js');
```

**Comment by vdemedes** [comment]
@shinnn This is brilliant.

**Comment by kevva** [comment]
Yup, seems to work.

**Comment by e-jigsaw** [comment]
Fantastic support!!
