### ISSUE TITLE
incompatible with ava 0.3.0: throws "process.send is not a function"

### ISSUE THREAD

**Issue by jokeyrhyme** [sindresorhus/gulp-ava#4]
Relates to: https://github.com/sindresorhus/ava/issues/143

If I explicitly use gulp-ava 0.2.x with ava 0.2.x, then everything works perfectly.

But if I use gulp-ava 0.2.x with ava 0.3.0, then it throws an error "process.send is not a function".

**Comment by sindresorhus** [comment]
gulp-ava haven't been updated to AVA 0.3.0 yet. I decided to skip it and bump it when AVA 0.4.0 is out (should be in a day).

**Comment by jokeyrhyme** [comment]
Awesome. Keep up the great work. :)
